### ISSUE TITLE
Question on SDL_CompileFromSPIRV and SDL_GpuCreateShader

### ISSUE THREAD

**Issue by RandyGaul** [TheSpydog/SDL_gpu_examples#17]
It seems a bit strange in this code snippet:

```cpp
if (SDL_GpuGetDriver(device) == SDL_GPU_DRIVER_VULKAN)
{
	shader = SDL_GpuCreateShader(device, &shaderInfo);
}
else
{
	shader = SDL_CompileFromSPIRV(device, &shaderInfo, SDL_FALSE);
}
```

It seems the design intent of these examples is to load up the SPIR-V blobs and cross compile them. This would make shipping the SPIR-V blobs a cross-platform shader solution. Is this correct? If so, why should I, as a user, need to ever call SDL_GpuCreateShader, unless I write a platform-dependent shader? Even if I'm targeting Vulkan, can I not just also call SDL_CompileFromSPIRV?

**Comment by TheSpydog** [comment]
It's not obvious due to the naming scheme, but SDL_CompileFromSPIRV is provided via the SDL_gpu_shadercross single-header library, which is a satellite library and not part of SDL_Gpu proper. (It used to be part of SDL_Gpu, but we removed it after the maintainers requested that we not rely on any specific external library like SPIRV-Cross. We'll probably end up changing the name to prevent future confusion.)

The only officially-provided way to set up shader data is to use SDL_GpuCreateShader with your shader bytecode data (generated either via offline shader compilers or some runtime shader cross-compilation pipeline). This allows for maximum flexibility for varying shader pipelines and is ultimately what's getting called inside of SDL_CompileFromSPIRV.

**Comment by flibitijibibo** [comment]
Filed 2 issues at the shadercross repo:

- https://github.com/flibitijibibo/SDL_gpu_shadercross/issues/4
- https://github.com/flibitijibibo/SDL_gpu_shadercross/issues/5
